image: node:18

stages:
  - precommit
  - build
  - test

before_script:
  - npm ci

precommit:
  stage: precommit
  script:
    - npx lint-staged

build:
  stage: build
  script:
    - echo "Pas de build à exécuter"

test:
  stage: test
  script:
    - npm run test

docker:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
  only:
    - branches